# Generated by Django 4.1.3 on 2022-11-07 14:43

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='none', max_length=50, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
