# Generated by Django 4.1.3 on 2022-11-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='main/files', upload_to='main/files'),
        ),
    ]
